webtalk_init -webtalk_dir D:/OneDrive/EECS 31L/Final/RISCV/RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_V_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec  9 04:06:28 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4bc2b42f-4552-4788-9df5-5815bf8c35ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "362ef4467f4c4d46b491438db21805f4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "93" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2093682696 -regid "" -xml D:/OneDrive/EECS 31L/Final/RISCV/RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_V_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/OneDrive/EECS 31L/Final/RISCV/RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_V_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/OneDrive/EECS 31L/Final/RISCV/RISCV.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_V_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
